### ISSUE TITLE
Does this work with Statamic 4?

### ISSUE THREAD

**Issue by Ash-LightAndShape** [doefom/restrict#3]
When trying to install this I get:

`- Root composer.json requires doefom/restrict * -> satisfiable by doefom/restrict[dev-main, v0.0.1, 9999999-dev].
    - doefom/restrict[dev-main, v0.0.1] require statamic/cms 3.2.* || 3.3.* || 3.4.* -> found statamic/cms[v3.2.0-beta.1, ..., 3.4.x-dev] but it conflicts with your root composer.json require (^4.0).`

It seems there's explicit versions defined in the package, does it need updating or does this not work in ^4.0 ?

**Comment by doefom** [comment]
@AshJ1987 thanks for reaching out! You're right, for now it only supports Statamic 3. I'll take a look and see what I can do, will update you in a bit.

**Comment by doefom** [comment]
@AshJ1987 should be all set now, feel free to give it another try. Updated the package to version 0.1.0 which now supports Statamic 4.

https://github.com/doefom/restrict/commit/9d483078b85e15ece0a0603ba1778c2a3fe5eba8
