### ISSUE TITLE
Restricts logged in users on the frontend too

### ISSUE THREAD

**Issue by Ash-LightAndShape** [doefom/restrict#4]
It turns out it blocks logged in users from accessing / even if they do not have CP access. Oddly, you can view entries in subpages, just not index which 404s

**Comment by doefom** [comment]
Hi @Ash-LightAndShape, thanks for reaching out! Can you provide some more detail about the problem you're facing? I don't quite understand what you mean yet.

**Comment by Ash-LightAndShape** [comment]
Hey yeah, so when it's installed if a user is logged in on the frontend they cannot view any pages that contain content from other users. 

So a user with no CP access but an account  with standard permissions will not be able to view / if it contains any entries

**Comment by doefom** [comment]
Alright, I understand the issue now. I'll try to fix this in the near future, unfortunately this might take a little while. But I'll keep you posted!

**Comment by de-raaf-media** [comment]
Any progress on this? I was really happy with your plugin until I encountered this issue ;-)

**Comment by de-raaf-media** [comment]
I may have an easy fix to bypass the restriction in the front-end. Currently testing it. Let me know if you want me to create a pull request if my tests go well.

**Comment by doefom** [comment]
@de-raaf-media Absolutely! Feel free to create a PR, really appreciate that.

**Comment by doefom** [comment]
@Ash-LightAndShape it took me ages but I refactored the addon and the issue should be fixed now. I'll close the issue. If the error still persists, please let me know and I'll take a look :)

**Comment by de-raaf-media** [comment]
Sorry, never got to this. Thanks for the fix! Looking at your code I think my solution was a bit hacky anyway.

**Comment by doefom** [comment]
Sure! Glad it's working now 😊
